import IFixture from "./IFixture";

export interface IElementEvent {
  assists: number,
  attempted_passes: number,
  big_chances_created: number,
  big_chances_missed: number,
  bonus: number,
  bps: number,
  clean_sheets: number,
  clearances_blocks_interceptions: number,
  completed_passes: number,
  creativity: string,
  dribbles: number,
  ea_index: number,
  element: number,
  errors_leading_to_goal: number,
  errors_leading_to_goal_attempt: number,
  fixture: number,
  fouls: number,
  goals_conceded: number,
  goals_scored: number,
  ict_index: string,
  id: number,
  influence: string,
  key_passes: number,
  kickoff_time: string,
  kickoff_time_formatted: string,
  loaned_in: number,
  loaned_out: number,
  minutes: number,
  offside: number,
  open_play_crosses: number,
  opponent_team: number,
  own_goals: number,
  penalties_conceded: number,
  penalties_missed: number,
  penalties_saved: number,
  recoveries: number,
  red_cards: number,
  round: number,
  saves: number,
  selected: number,
  tackled: number,
  tackles: number,
  target_missed: number,
  team_a_score: number,
  team_h_score: number,
  threat: string,
  total_points: number,
  transfers_balance: number,
  transfers_in: number,
  transfers_out: number,
  value: number,
  was_home: boolean,
  winning_goals: number,
  yellow_cards: number
}

export default interface IElement {
  explain: {
    explain: {
      assists?: { name: string, points: number, value: number },
      bonus?: { name: string, points: number, value: number },
      bps?: { name: string, points: number, value: number },
      clean_sheets?: { name: string, points: number, value: number },
      goals_conceded?: { name: string, points: number, value: number },
      goals_scored?: { name: string, points: number, value: number },
      minutes?: { name: string, points: number, value: number },
      own_goals?: { name: string, points: number, value: number },
      penalties_missed?: { name: string, points: number, value: number },
      penalties_saved?: { name: string, points: number, value: number },
      red_cards?: { name: string, points: number, value: number },
      saves?: { name: string, points: number, value: number },
      total_points?: { name: string, points: number, value: number },
      yellow_cards?: { name: string, points: number, value: number }
    }[],
    fixture: IFixture[]
  }[],
  fixtures: IFixture[],
  fixtures_summary: IFixture[],
  history: IElementEvent[],
  history_past: {
    assists: number,
    bonus: number,
    bps: number,
    clean_sheets: number,
    creativity: string,
    ea_index: number,
    element_code: number,
    end_cost: number,
    goals_conceded: number,
    goals_scored: number,
    ict_index: string,
    id: number,
    influence: string,
    minutes: number,
    own_goals: number,
    penalties_missed: number,
    penalties_saved: number,
    red_cards: number,
    saves: number,
    season: number,
    season_name: string,
    start_cost: number,
    threat: string,
    total_points: number,
    yellow_cards: number
  }[],
  history_summary: IElementEvent[]
}